spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb.doromolll.xyz:9009/wss_car
    username: root
    password: 534534534111
    hikari:
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

